import { CarsBrand } from "../container/types";

export const data: CarsBrand[] = [
  {
    name: "Agera",
    id: "agera",
    image: "xMyu5VQ4su4",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Audi",
    id: "audi",
    image: "7lGiQDLnkUs",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Bentley",
    id: "bentley",
    image: "mUYlnOev7xc",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "BMW",
    id: "bmw",
    image: "w77TcvuhtWE",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Ferrari",
    id: "ferrari",
    image: "3akA0XDg1_g",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Ford",
    id: "ford",
    image: "lX2YG5w4_gs",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "GTR",
    id: "gtr",
    image: "keBp2WcK86U",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Hummer",
    id: "hummer",
    image: "G3_yUJQTYVA",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Jaguar",
    id: "jaguar",
    image: "7tfu2dq8Ljk",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Lamborghini",
    id: "lamborghini",
    image: "HBop_t9V9kM",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Maserati",
    id: "maserati",
    image: "2eMJDJM9vxk",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Mini Cooper",
    id: "miniCooper",
    image: "oCG2nqQPLZs",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Range Rover",
    id: "rangeRover",
    image: "BYdnBgF5Z_M",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
  {
    name: "Rolls-Royce",
    id: "rollsRoyce",
    image: "wx-XBLK1bWA",
    carList: [
      {
        name: "Car-1",
        id: "Car_1",
        image: "m3m-lnR90uM",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-2",
        id: "Car_2",
        image: "vw0AmpZvHZg",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-3",
        id: "Car_3",
        image: "p7tai9P7H-s",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-4",
        id: "Car_4",
        image: "fwYZ3B_QQco",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-5",
        id: "Car_5",
        image: "N7RiDzfF2iw",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-6",
        id: "Car_6",
        image: "qyfco1nfMtg",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
      {
        name: "Car-7",
        id: "Car_7",
        image: "3ZUsNJhi_Ik",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-8",
        id: "Car_8",
        image: "f_SDCASisgs",
        price: "20000000",
        cc: "500 cc",
        type: "Automatic",
        fuelType: "Diesel",
        speed: "10.24 kmpl",
      },
      {
        name: "Car-9",
        id: "Car_9",
        image: "X16zXcbxU4U",
        price: "20000000",
        cc: "998 cc",
        type: "Manual",
        fuelType: "Petrol",
        speed: "25.24 kmpl",
      },
    ],
  },
];
